# Site settings
title: "Hacking the Library"
email: steele@osteele.com
description: >
  Let’s create a new kind of Library.

baseurl: "/" # the subpath of your site, e.g. /blog/
# url: "http://hackingthelibrary.org"
timezone: America/New_York

# Google Custom Search Engine
# gcse_id: 011154276211498969066:uccvhxtwt-q

collections:
  days:
    output: true
    permalink: /day/:path/
  assignments:
    output: true
    permalink: /assignments/:path/
  pages:
    output: true
    permalink: /:path/

course:
  title: "Special Topics in Computing: Hacking the Library"
  number: ENGR3599

defaults:
  - scope:
      path: ""
      type: assignments
    values:
      layout: assignment
  - scope:
      path: ""
      type: days
    values:
      layout: day
  - scope:
      path: ""
      type: pages
    values:
      layout: page

gems:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
